os: linux
language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
     - gdb
     - apport
     - gcc-7
     - g++-7
     - cmake
     - libc++1
     - clang-5.0
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-trusty-5.0
     - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
     - key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

python:
  - "3.6"

matrix:
  include:
  - env: c_compiler=clang cxx_compiler=clang++ config=Debug
  - env: c_compiler=gcc-7 cxx_compiler=g++-7 config=Debug

before_install:
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - ${c_compiler} -v && ${cxx_compiler} -v && cmake --version && make --version && python --version
  - cmake/build.sh ${config} x64 ${c_compiler} ${cxx_compiler} "-DBUILD_IN_CONSOLE_MODE=1 -DBUILD_WINDOW_FRAMEWORK=0"
  - ulimit -c unlimited -S
  - cd build/${config}-x64-${c_compiler}
  - make tests -j2 --keep-going
  - ls -l
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/../dev/${EXECUTABLE_NAME} core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notfications:
  email: false
