os: linux
language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
     - gdb
     - apport
     - gcc-7
     - g++-7
     - cmake
    sources:
     - ubuntu-toolchain-r-test

python:
  - "3.6"

matrix:
  include:
  - env: c_compiler=clang cxx_compiler=clang++ config=Debug other_cmake_flags="-DBUILD_OPENAL=0"
  - env: c_compiler=gcc-7 cxx_compiler=g++-7 config=Debug other_cmake_flags=""

before_install:
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - |
    if [[ "${c_compiler}" == "clang" ]]; then
      clang++ -v
      mkdir TMP_CLANG
      cd TMP_CLANG
      git clone https://chromium.googlesource.com/chromium/src/tools/clang
      cd ..
      TMP_CLANG/clang/scripts/update.py
      ln -s ./third_party/llvm-build/Release+Asserts/bin/clang
      ln -s ./third_party/llvm-build/Release+Asserts/bin/clang++
      sudo apt-get install -y libc++-dev libc++abi-dev
    fi
  - ${c_compiler} -v && ${cxx_compiler} -v && cmake --version && make --version && python --version
  - cmake/build.sh ${config} x64 ${c_compiler} ${cxx_compiler} "-DBUILD_IN_CONSOLE_MODE=1 -DBUILD_WINDOW_FRAMEWORK=0 ${other_cmake_flags}"
  - ulimit -c unlimited -S
  - cd build/${config}-x64-${c_compiler}
  - make VERBOSE=1 tests -j2 --keep-going
  - ls -l
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/../dev/${EXECUTABLE_NAME} core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notfications:
  email: false
