os: linux
language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
     - gdb
     - apport
     - gcc-7
     - g++-7
     - cmake
    sources:
      - ubuntu-toolchain-r-test
compiler:
 - gcc
env:
  - config=Debug
python:
  - "3.6"
before_install:
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - gcc -v && g++ -v && cmake --version && make --version && python --version
  - cmake/build.sh ${config} x64 gcc-7 g++-7 "-DBUILD_IN_CONSOLE_MODE=1 -DBUILD_WINDOW_FRAMEWORK=0"
  - ulimit -c unlimited -S
  - cd build/${config}-x64-gcc-7
  - make tests -j2 --keep-going
  - ls -l
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/../dev/${EXECUTABLE_NAME} core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notfications:
  email: false
