dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version && make --version
  # Run your build commands next
  - mkdir dev
  - cd dev
  - cmake -DUNIX=ON -DBUILD_OPENGL=OFF -DBUILD_VERSION_FILE_GENERATOR=OFF -DBUILD_HTTP_REQUESTS=OFF -DADD_COMMAND_TO_ARCHIVE_BUILDS_IN_RELEASE=OFF -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..
  - make --keep-going VERBOSE=1
  - ./Hypersomnia --unit-tests-only
  
notfications:
  email: false
