dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
python:
  - "3.6"
script:
  # Check versions
  - gcc -v && g++ -v && cmake --version && make --version
  - python --version
  # Run your build commands next
  - mkdir dev
  - cd dev
  # - We don't need to allocate entities statically for performance as this is just a test.
  # - We don't need to archive builds, either.
  - cmake -DUNIX=ON -DCMAKE_BUILD_TYPE=Release -DHYPERSOMNIA_BARE=ON -DSTATICALLY_ALLOCATE_ENTITIES_NUM=0 -DSTATICALLY_ALLOCATE_ASSETS=0 -DOUTPUT_LOG_TO_STDOUT=1 -DBUILD_HTTP_REQUESTS=OFF -DADD_COMMAND_TO_ARCHIVE_BUILDS_IN_RELEASE=OFF -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..
  - make --keep-going VERBOSE=1
  - ./Hypersomnia --unit-tests-only
  
notfications:
  email: false
