os: linux
language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
     - gdb
     - apport
     - gcc-7
     - g++-7
     - cmake
    sources:
      - ubuntu-toolchain-r-test
compiler:
 - gcc
env:
  - config=Debug
python:
  - "3.6"
before_install:
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - gcc -v && g++ -v && cmake --version && make --version && python --version
  - mkdir dev
  - cd dev
  # - We don't need to allocate entities statically for performance as this is just a test.
  # - We don't need to archive builds, either.
  - cmake -DUNIX=ON -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_C_FLAGS="-m64" -DCMAKE_BUILD_TYPE=${config} -DADD_MCMODEL_LARGE_FLAG=OFF -DHYPERSOMNIA_BARE=ON -DSTATICALLY_ALLOCATE_ENTITIES_NUM=0 -DSTATICALLY_ALLOCATE_ASSETS=0 -DSTATICALLY_ALLOCATE_BAKED_FONTS=0 -DBUILD_IN_CONSOLE_MODE=1 -DBUILD_HTTP_REQUESTS=OFF -DADD_COMMAND_TO_ARCHIVE_BUILDS_IN_RELEASE=OFF -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..
  - make -j2 --keep-going
  - cd ../hypersomnia
  - |
    if [[ "${config}" == "Debug" ]]; then 
      EXECUTABLE_NAME=Hypersomnia-Debug
    else
      EXECUTABLE_NAME=Hypersomnia
    fi
    
  - ulimit -c unlimited -S
  - ../dev/${EXECUTABLE_NAME} --unit-tests-only
  - ls -l
  - if [[ ${RESULT} != 139 ]]; then echo "expected segfault and 139 exit but instead exited with ${RESULT}" && exit 1; fi;
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notfications:
  email: false
