sudo: true
dist: precise
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
env:
  - config=Debug
python:
  - "3.6"
before_install:
 # What is the current file size max for core files?
 # It is usually 0, which means no core file will be dumped if there is a crash 
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - mkdir ./mason/
  - curl -sSfL https://github.com/mapbox/mason/archive/v0.2.0.tar.gz | tar --gunzip --extract --strip-components=1 --directory=./mason/
  # install gdb via mason
  - ./mason/mason install gdb 7.12
  # put GDB on PATH
  - export PATH=$(./mason/mason prefix gdb 7.12)/bin:${PATH}
  # install logbt
  - curl -sSfL https://github.com/mapbox/logbt/archive/v1.6.0.tar.gz | tar --gunzip --extract --strip-components=2 --exclude="*md" --exclude="test*" --directory=.

  - gcc -v && g++ -v && cmake --version && make --version
  - python --version
  # Run your build commands next
  - mkdir dev
  - cd dev
  # - We don't need to allocate entities statically for performance as this is just a test.
  # - We don't need to archive builds, either.
  - cmake -DUNIX=ON -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_C_FLAGS="-m64" -DCMAKE_BUILD_TYPE=${config} -DADD_MCMODEL_LARGE_FLAG=OFF -DHYPERSOMNIA_BARE=ON -DSTATICALLY_ALLOCATE_ENTITIES_NUM=0 -DSTATICALLY_ALLOCATE_ASSETS=0 -DSTATICALLY_ALLOCATE_BAKED_FONTS=0 -DBUILD_IN_CONSOLE_MODE=1 -DBUILD_HTTP_REQUESTS=OFF -DADD_COMMAND_TO_ARCHIVE_BUILDS_IN_RELEASE=OFF -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..
  - make -j2 --keep-going
  - cd ../hypersomnia
  - |
    if [[ "${config}" == "Debug" ]]; then 
      EXECUTABLE_NAME=Hypersomnia-Debug
    else
      EXECUTABLE_NAME=Hypersomnia
    fi
    
  - sudo bash -c "echo '/tmp/logbt-coredumps/core.%p.%E' > /proc/sys/kernel/core_pattern"
  - RESULT=0
  - ./logbt ../dev/${EXECUTABLE_NAME} --unit-tests-only

notfications:
  email: false
