os: linux
language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
     - gdb
     - apport
     - gcc-7
     - g++-7
     - clang-7
     - lld-7
     - libc++1-7
     - libc++abi1-7
     - cmake
     - ninja-build
     - libxcb-keysyms1
     - libxcb-keysyms1-dev
     - libxi6
     - libxi-dev
     - alsa-oss
     - osspd-alsa
     - osspd
     - libasound2
     - libasound2-dev
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-trusty-7

python:
  - "3.6"

matrix:
  include:
  - env: c_compiler=clang cxx_compiler=clang++ config=Debug other_cmake_flags=""
    compiler: clang
#  - env: c_compiler=gcc-7 cxx_compiler=g++-7 config=Debug other_cmake_flags=""
#    compiler: gcc
#  - env: c_compiler=gcc-7 cxx_compiler=g++-7 config=RelWithDebInfo other_cmake_flags=""
#    compiler: gcc

before_install:
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true

script:
  - ${c_compiler} -v && ${cxx_compiler} -v && cmake --version && make --version && python --version
  - export CC=${c_compiler}
  - export CXX=${cxx_compiler}
  - cmake/build.sh ${config} x64 ${c_compiler} ${cxx_compiler} "-DBUILD_IN_CONSOLE_MODE=1 ${other_cmake_flags}"
  - ulimit -c unlimited -S
  - pushd build/current
  - ninja tests -k 0
  - ls -l
  - popd
  - ls -l hypersomnia
  - cmake/print_bt_if_core_found.sh hypersomnia/core

notfications:
  email: false
