version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2017 Preview
configuration: Release
build:
  verbosity: detailed

clone_script:
  - git clone --depth 1 --recurse-submodules https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

notifications:
  - provider: Email
    to:
      - patryk.czachurski@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

artifacts:
  - path: Hypersomnia-x64.zip
    name: Hypersomnia (64-bit)

before_build:
  - |
  call "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  cd C:\projects\hypersomnia

build_script:
  - ps: |
  mkdir nin
  cd nin
  mkdir $env:CONFIGURATION
  cd $env:CONFIGURATION
  cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_LINKER=lld-link -DARCHITECTURE="x64" -DCMAKE_BUILD_TYPE=$env:CONFIGURATION -DGENERATE_DEBUG_INFORMATION=0 ../..
  ninja

test_script:
  - ps: |
  cd ../../hypersomnia
  & ../cmake/test_and_pack.ps -configuration $env:CONFIGURATION -console_mode 0

