version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2017 Preview
configuration: Release
build:
  parallel: true                  # enable MSBuild parallel builds
  project: dev/Hypersomnia.sln      # path to Visual Studio solution or project
  verbosity: minimal
install:
  - git submodule update --init --recursive

test:
  assemblies:
    only:
      - '**\*.Hypersomnia.exe'
      - '**\*.Hypersomnia-Debug.exe'

before_build:
  - mkdir dev
  - cd dev
  - cmake -DBUILD_IN_CONSOLE_MODE=1 ..

test_script:
  - cd hypersomnia
  - call "../dev/$env:CONFIGURATION/Hypersomnia.exe" --unit-tests-only
